name: cl-som-imx7-kernel
version: 4.1.15-1
summary: CompuLab Deveices kernel for cl-som-imx7
description: CompuLab Deveices kernel for cl-som-imx7
type: kernel
architectures: [ armhf ]

parts:
    kernel:
        plugin: kernel
        source: https://github.com/compulab-yokneam/cl-som-imx7.git
        source-branch: devel
        source-type: git
        kdefconfig: [compulab_imx7_defconfig]
        kconfigs:
            - CONFIG_LOCALVERSION="-uc-1"
            - CONFIG_DEBUG_INFO=n
            - CONFIG_SQUASHFS=m
            - CONFIG_DEVPTS_MULTIPLE_INSTANCES=y
            - CONFIG_SQUASHFS_LZ4=y
            - CONFIG_SQUASHFS_LZO=y
            - CONFIG_SQUASHFS_XZ=y
            - CONFIG_SQUASHFS_4K_DEVBLK_SIZE=y
            - CONFIG_SQUASHFS_EMBEDDED=y
            - CONFIG_CGROUP_DEBUG=y
            - CONFIG_CGROUP_FREEZER=y
            - CONFIG_CGROUP_DEVICE=y
            - CONFIG_CPUSETS=y
            - CONFIG_CGROUP_CPUACCT=y
            - CONFIG_MEMCG=y
            - CONFIG_MEMCG_SWAP=y
            - CONFIG_MEMCG_KMEM=y
            - CONFIG_CGROUP_PERF=y
            - CONFIG_BLK_CGROUP=y
            - CONFIG_DEBUG_BLK_CGROUP=y
            - CONFIG_SECCOMP=y

        kernel-initrd-modules:
            - squashfs
        kernel-image-target: zImage
        kernel-device-trees:
             - imx7d-sbc-iot-imx7
             - imx7d-sbc-imx7
        build-packages: [bc, kmod, cpio]
        install: |
           mkimage -A arm -O Linux -T ramdisk -d $SNAPCRAFT_PART_INSTALL/initrd.img $SNAPCRAFT_PART_INSTALL/ramdisk.img
           cp $SNAPCRAFT_PART_INSTALL/ramdisk.img $SNAPCRAFT_PART_INSTALL/initrd.img

    firmware:
        source: git://git.ti.com/wilink8-wlan/linux-firmware.git
        plugin: dump
        organize:
           LICENCE.ti-connectivity: firmware/LICENCE.ti-connectivity
           ti-connectivity: firmware/ti-connectivity
        stage:
           - firmware/*

    firmware-bt:
        source: git://git.ti.com/ti-bt/service-packs.git
        plugin: dump
        organize:
             initscripts/TIInit_11.8.32.bts: firmware/ti-connectivity/TIInit_11.8.32.bts
        stage:
           - firmware/*
